### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by g4s8** [g4s8/xembly-js#1]
Implement Xembly engine for JS

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.4`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.4`

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#2](https://github.com/g4s8/xembly-js/issues/2) is still not solved.

**Comment by g4s8** [comment]
done

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#2](https://github.com/g4s8/xembly-js/issues/2), [#3](https://github.com/g4s8/xembly-js/issues/3) are still not solved.

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.7`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.7`
